// Generated by https://quicktype.io

export interface Oferta {
  id:                string;
  titulo:            string;
  empresa:           string;
  descripcion:       string;
  ubicacion:         string;
  tipo:              Tipo;
  salario:           string;
  requisitos:        string[];
  fecha_publicacion: string;
  fecha_cierre:      string;
}

export enum Tipo {
  MedioTiempo = "Medio tiempo",
  Prácticas = "Prácticas",
  TiempoCompleto = "Tiempo completo",
}
